aws:
  region: region-name
  s3:
    buckets:
      user: bucket-name

spring:
  datasource:
    username: db-user-name
    password: db-user-password
    url: host-url
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB